name: iOS Testing
on:
  pull_request:
    branches:
    - development
    - master
    paths-ignore:
    - 'androidApp/**'

jobs:
  test:
    name: Testing iOS app
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Testing iOS app
        working-directory: ./iosApp
        run: fastlane tests
